name: Period Healthcheck of application

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  healthcheck_deployment:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://christmas-mono-repo.herokuapp.com/ping
          follow-redirect: no
          max-attempts: 3
          retry-delay: 5s